development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 2
  username: ajrom
  password: Romaniello12

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: production
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
