development:
  adapter: postgresql
  database: development
  host: localhost
  user: username
  password: password
  encoding: unicode
  pool: 5

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  encoding: unicode
  pool: 5
